name: Sync Fork
on:
  schedule:
    - cron: '0 0 1 * *' # 每月1号凌晨自动同步
  workflow_dispatch: # 手动触发
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          # 以下是根据报错修改后的参数名
          upstream_sync_repo: DIYgod/RSSHub
          upstream_sync_branch: master
          target_sync_branch: master
          # 如果你想测试，可以暂时加上下面这行跳过一些验证
          test_mode: false
